- name: Build debug APK
  run: gradle assembleDebug

- name: Rename APK
  run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Fizika-Inicijalni-Test-2.apk

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: Fizika-Inicijalni-Test-2
    path: app/build/outputs/apk/debug/Fizika-Inicijalni-Test-2.apk
